### ISSUE TITLE
Question: What's the percentage chance a Plague Bee will cure a Zombie Villager?

### ISSUE THREAD

**Issue by riskable** [rwtema/Careerbees#12]
Testing out the new changes in Creative Mode I noticed that the Plague Bee didn't work to cure Zombie Villagers most of the time during the day (even if covered/protected from the sun) but worked decently well at curing them at night (but occasionally would still kill them).  What controls this outcome?  Is it something in Career Bees or is it just a vanilla mechanic?

Just trying to get the details for my mod spotlight (which is nearing completion!).  Thanks for your assistance and an awesome mod.

**Comment by rwtema** [comment]
There's no chances or time conditions required, they just need to be nearby and be acted on. The bees however are not nocturnal and require the diurnal gene or a lighting upgrade.

**Comment by riskable** [comment]
Thanks!  That explains a lot, actually.  Much more interesting answer than I was expecting.
