### ISSUE TITLE
Mad Scince Bee - Revelation 1.6

### ISSUE THREAD

**Issue by Kettzer** [rwtema/Careerbees#15]
hi,

how do you mean 
Science + Engineer (Must have been a nearby explosion in the last 10 seconds)

If I put a science + engineer in an industrial apiary (Mod Gendustry).
Must the explosion before I put the bees in or after I put the bees in, or at the end of the lifespan.

At this Moment I don't get this Mad Science Bee.
I don't get the Mad Science Bee with the Advance Mutragon from Gendustrie, they won't fit in.

**Comment by LezChap** [comment]
You can't get this mutation in the Mutatron from Gendustry.  I did it by setting up a machine to dispense/light a TNT into a body of water (so no block damage) every ~5 seconds within range of the Apiary (about 4-5 blocks away?), and turned it on right before the bees died in an Industrial Apiary from Gendustry.  I think it set off about 5 TNT before the queen died, and I got a perfectly mutated princess.  I think I was on 1.8 Revelation when I finally got around to this, but I don't think the breeding/mutation mechanic was changed between the mod versions in 1.6 and 1.8.
