### ISSUE TITLE
Feature Request: Collecting Bees use item frames as whitelist

### ISSUE THREAD

**Issue by riskable** [rwtema/Careerbees#2]
I'm currently playing on an FTB Revelation server and having a blast with Career Bees!  Only I have a problem:  Trying to work out the range of the Collecting Bee in order to ensure it only picks up certain items is a bit difficult.  I only need it to pick up the drops from the Butcher Bee (which come thanks to the Husbandry Bee!) but it ends up picking up anything I mine or happen to drop nearby (especially fast thanks to the Temporal Bee!).

It would be nice if the Collecting Bee worked like Botania's Hopperhock in that it would only pick up items that you have in an Item Frame placed on the Apiary containing the Collecting Bee.  It would make routing items a heck of a lot easier and also make for some interesting bee-based automation!  Alternatively, if it placed items in local inventories with Item Frames placed on them that would be even better!  Or that could be it's own bee:  The Sorting Bee (which would be bred from a Collecting Bee and something else, of course).

For example, right now I'm making Red Sand from a Nuclearcraft Cobblestone Generator going into a Thermal Expansion Pulverizer which outputs to a Gadgetry Block Placer which converts that sand into Clay via Botania's Clayconia flower which then gets picked up by a Hopperhock and placed into a Crafty Crate which makes it into a clay block which then drops that clay block into a Hopper which feeds into a Career Bees Flower Pedestal which allows the Smelter Bee to convert the clay block into a Terracotta block which drops into a Hopper which feeds into a Botania Open Crate which drops it onto a Mana Pool over an Alchemy Catalyst which turns it into Red Sand which gets picked up by a Hopperhock and placed into an Ender Chest which feeds into my ME network!  Muahaha!

So anyway, it would be wicked if I could just skip the Hopperhocks altogether and just place Collecting Bees (being managed by Yenta Princesses!) in Apiaries nearby with item frames on Hoppers telling them where to place stuff *or* just have the Collecting Bees only collect the items in frames on the sides of their Apiary.  Either way would be awesome.

Thanks for the amazingly mod!  I'm starting to get really fancy with these bees!

**Comment by rwtema** [comment]
Implemented by Commit 76874f47a1498a8a48982ba6ade94e8c3ebc9f40
