### ISSUE TITLE
Question: Bee Gun with Queen or Princess provides unlimited bees...  Intentional?

### ISSUE THREAD

**Issue by riskable** [rwtema/Careerbees#8]
Just a quick question about your amazing mod:  I noticed that when putting a Queen or Princess Bee in the (awesome/hilarious, muwahaha!) Bee Gun this provides unlimited bees (beesources?) whereas using drones results in the drones being consumed.  Is this intentional or a bug?

A Queen producing unlimited bees makes sense but a Princess?  Not so sure (not that it makes all that much of a difference since you can just make a Queen from a Princess fairly trivially).

You can close this issue with your answer.  Thanks!

**Comment by rwtema** [comment]
Intended.

**Comment by riskable** [comment]
Thanks for answering my question.  This will simplify my spotlight because I've already got lots of footage demonstrating the Bee-Bee Gun with queens in it =)
